apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: string-passing-
  namespace: argo
  labels:
    app: string-passing
spec:
  serviceAccountName: argo-workflow
  entrypoint: main
  ttlStrategy:
    secondsAfterCompletion: 3600
  templates:
  - name: main
    steps:
    - - name: produce-message
        template: step1
    - - name: check-message
        template: gate
        arguments:
          parameters:
          - name: message
            value: "{{steps.produce-message.outputs.parameters.message}}"
    - - name: consume-message
        template: step2
        when: "{{steps.check-message.outputs.parameters.allow}} == true"
        arguments:
          parameters:
          - name: message
            value: "{{steps.produce-message.outputs.parameters.message}}"
  - name: step1
    retryStrategy:
      limit: 3
      retryPolicy: OnError
      backoff:
        duration: 3s
        factor: 2
        maxDuration: 30s
    script:
      image: python:3.9
      command: [python]
      source: |
        print("Hello from step 1!")
        with open("/tmp/message.txt", "w") as f:
            f.write("Hello from step 1!")
    outputs:
      parameters:
      - name: message
        valueFrom:
          path: /tmp/message.txt
  - name: gate
    inputs:
      parameters:
      - name: message
    script:
      image: python:3.9
      command: [python]
      source: |
        msg = "{{inputs.parameters.message}}"
        print("Gate evaluating message:", msg)
        allow = "true" if "Hello" in msg else "false"
        print("Allow =", allow)
        with open("/tmp/allow.txt","w") as f:
            f.write(allow)
    outputs:
      parameters:
      - name: allow
        valueFrom:
          path: /tmp/allow.txt
  - name: step2
    inputs:
      parameters:
      - name: message
    script:
      image: python:3.9
      command: [python]
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "250m"
          memory: "128Mi"
      source: |
        print("Step 2 received message:", "{{inputs.parameters.message}}")
