apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: conditional-step-
  namespace: argo
spec:
  entrypoint: main
  serviceAccountName: argo-workflow
  templates:
  - name: gate
    steps:
    - - name: wait-for-approval
        template: wait-for-approval
    - - name: set-allow
        template: set-allow
    outputs:
      parameters:
      - name: allow
        valueFrom:
          parameter: '{{steps.set-allow.outputs.result}}'
  - name: wait-for-approval
    outputs:
      parameters:
      - name: approved
        valueFrom:
          supplied: {}
    suspend: {}
  - name: set-allow
    inputs:
      parameters:
      - name: approved
    script:
      image: python:3.9
      source: |-
        import os
        import sys
        sys.path.append(os.getcwd())
        import json
        try: approved = json.loads(r'''{{inputs.parameters.approved}}''')
        except: approved = r'''{{inputs.parameters.approved}}'''

        return 'true' if approved == 'true' else 'false'
      command:
      - python
  - name: main
    steps:
    - - name: produce-message
        template: step1
    - - name: check-message
        template: gate
    - - name: consume-message
        template: step2
        when: '{{steps.check-message.outputs.parameters.allow}} == true'
  - name: step1
    script:
      image: python:3.9
      source: |-
        import os
        import sys
        sys.path.append(os.getcwd())
        return 'Hello from step 1!'
      command:
      - python
  - name: step2
    inputs:
      parameters:
      - name: message
    script:
      image: python:3.9
      source: |-
        import os
        import sys
        sys.path.append(os.getcwd())
        import json
        try: message = json.loads(r'''{{inputs.parameters.message}}''')
        except: message = r'''{{inputs.parameters.message}}'''

        print('Step 2 received message:', message)
      command:
      - python
  ttlStrategy:
    secondsAfterCompletion: 3600

