#kubectl port-forward svc/jaeger 16686:16686
# http://localhost:16686

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.jaeger.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.jaeger.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.jaeger.name }}
    spec:
      containers:
        - name: jaeger
          image: {{ .Values.jaeger.image }}
          imagePullPolicy: {{ .Values.jaeger.pullPolicy }}
          env:
            # Włącz OTLP gRPC + HTTP w Jaeger all-in-one
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
          ports:
            - name: otlp-grpc
              containerPort: 4317
            - name: otlp-http
              containerPort: 4318
            - name: ui
              containerPort: {{ .Values.jaeger.uiPort }}
          # możesz dodać resources / storage jeśli chcesz coś więcej niż demo
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jaeger.name }}
spec:
  selector:
    app: {{ .Values.jaeger.name }}
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: ui
      port: {{ .Values.jaeger.uiPort }}
      targetPort: {{ .Values.jaeger.uiPort }}
  type: ClusterIP