{{- if .Values.loki.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.loki.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.loki.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.loki.name }}
    spec:
      containers:
        - name: loki
          image: {{ .Values.loki.image }}
          imagePullPolicy: {{ .Values.loki.pullPolicy }}
          args:
            - "-config.file=/etc/loki/config/config.yml"
          ports:
            - name: http
              containerPort: {{ .Values.loki.port }}
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki/config
            - name: loki-data
              mountPath: /loki
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
        - name: loki-data
          emptyDir: {}   # demo – brak persystentnego storage

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  config.yml: |
    auth_enabled: false

    server:
      http_listen_port: {{ .Values.loki.port }}

    common:
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory

    # wymagane dla native OTLP + structured metadata:
    # schema v13 + store: tsdb
    schema_config:
      configs:
        - from: 2025-01-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    storage_config:
      filesystem:
        directory: /loki/chunks

    limits_config:
      allow_structured_metadata: true
      ingestion_rate_mb: {{ .Values.loki.ingestionRateMB }}
      ingestion_burst_size_mb: {{ .Values.loki.ingestionBurstMB }}

      # globalna retencja – logi trzymane około 1h
      # (Ty masz w values.yaml "1h")
      retention_period: {{ .Values.loki.retentionPeriod }}

    compactor:
      working_directory: /loki/compactor
      compaction_interval: 5m
      retention_enabled: true
      retention_delete_delay: 5m
      # dla filesystem używamy delete_request_store=filesystem
      delete_request_store: filesystem

    ruler:
      storage:
        type: local
        local:
          directory: /loki/rules

    querier:
      max_concurrent: 20

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.loki.name }}
spec:
  selector:
    app: {{ .Values.loki.name }}
  ports:
    - name: http
      port: {{ .Values.loki.port }}
      targetPort: {{ .Values.loki.port }}
  type: ClusterIP
{{- end }}