apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-collector
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

      filelog:
        include:
          - /var/log/containers/*_{{ .Release.Namespace }}_{{ .Values.serviceA.name }}-*.log
          - /var/log/containers/*_{{ .Release.Namespace }}_{{ .Values.serviceB.name }}-*.log
          - /var/log/containers/*_{{ .Release.Namespace }}_{{ .Values.serviceC.name }}-*.log
        start_at: beginning
        include_file_path: true
        include_file_name: false
        operators:

          - type: json_parser
            id: cri_json
            parse_from: body
            on_error: send_quiet


          - type: move
            id: log_to_body
            from: attributes.log
            to: body
            on_error: send_quiet

          # 2) wyciągamy pod / namespace / container z nazwy pliku
          # /var/log/containers/<pod>_<ns>_<container>-<id>.log
          - type: regex_parser
            id: parse_filepath
            parse_from: attributes["log.file.path"]
            regex: ".*/(?P<pod_name>[^_]+)_(?P<namespace_name>[^_]+)_(?P<container_name>[^-]+-[^-]+)-.*\\.log"
            on_error: send_quiet

          - type: move
            id: container_to_service
            from: attributes.container_name
            to: attributes.service_name
            on_error: send_quiet

          - type: move
            id: namespace_to_service_namespace
            from: attributes.namespace_name
            to: attributes.service_namespace
            on_error: send_quiet

          # 3) trace_id / span_id / trace_sampled z body
          - type: regex_parser
            id: extract_trace_id
            parse_from: body
            regex: "trace_id=(?P<trace_id>[^ ]+)"
            on_error: send_quiet

          - type: regex_parser
            id: extract_span_id
            parse_from: body
            regex: "span_id=(?P<span_id>[^ ]+)"
            on_error: send_quiet

          - type: regex_parser
            id: extract_trace_sampled
            parse_from: body
            regex: "trace_sampled=(?P<trace_sampled>[^\\] ]+)"
            on_error: send_quiet

          # 4) wytnij prefix i zostaw sam message
          # wariant 1 – typowy log z 3 blokami w []
          # 2025-... INFO [__main__] [app.py:27] [trace_id=...] - MESSAGE
          - type: regex_parser
            id: extract_msg_format1
            parse_from: body
            regex: '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}\s+\S+\s+\[[^\]]*]\s+\[[^\]]*]\s+\[[^\]]*]\s+-\s+(?P<msg>.*)$'
            on_error: send_quiet

          # wariant 2 – fallback: weź wszystko po ostatnim " - "
          - type: regex_parser
            id: extract_msg_fallback
            parse_from: body
            if: 'attributes.msg == nil'
            regex: '^.* - (?P<msg>.*)$'
            on_error: send_quiet

          - type: move
            id: msg_to_body
            from: attributes.msg
            to: body
            on_error: send_quiet

    processors:
      transform/logs:
        log_statements:
          - context: log
            statements:
              # wrzuć nazwy serwisów do resource – Loki nie będzie używał "unknown_service"
              - set(resource.attributes["service.name"], attributes["service_name"]) where attributes["service_name"] != nil
              - set(resource.attributes["service.namespace"], attributes["service_namespace"]) where attributes["service_namespace"] != nil
              - set(resource.attributes["service.instance.id"], attributes["pod_name"]) where attributes["pod_name"] != nil

              # trace/span w ładniejszych kluczach
              - set(attributes["trace.id"], attributes["trace_id"]) where attributes["trace_id"] != nil
              - set(attributes["span.id"], attributes["span_id"]) where attributes["span_id"] != nil

      batch: {}

    exporters:
      otlphttp/logs:
        endpoint: "http://{{ .Values.loki.name }}:{{ .Values.loki.port }}/otlp"
        tls:
          insecure: true

      otlp/jaeger:
        endpoint: "jaeger:4317"
        tls:
          insecure: true

      debug/logs:
        verbosity: detailed

    service:
      telemetry:
        logs:
          level: debug
      pipelines:
        logs:
          receivers: [filelog]
          processors: [transform/logs, batch]
          exporters: [debug/logs, otlphttp/logs]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/jaeger]
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector
spec:
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      serviceAccountName: otel-collector
      containers:
        - name: otel-collector
          image: {{ .Values.otelCollector.image }}
          imagePullPolicy: {{ .Values.otelCollector.pullPolicy }}
          args: ["--config=/etc/otelcol/config.yaml"]
          ports:
            - name: otlp-grpc
              containerPort: 4317
            - name: otlp-http
              containerPort: 4318
          volumeMounts:
            - name: collector-config
              mountPath: /etc/otelcol
            - name: varlogcontainers
              mountPath: /var/log/containers
            - name: varlogpods
              mountPath: /var/log/pods
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
          resources: {}
      volumes:
        - name: collector-config
          configMap:
            name: otel-collector-config
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
            type: Directory
        - name: varlogpods
          hostPath:
            path: /var/log/pods
            type: Directory
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  selector:
    app: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
  type: ClusterIP