{{- if .Values.otelOperatorCollector.enabled }}
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: demo
spec:
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch: {}
    exporters:
      debug:
        verbosity: basic

      otlphttp/logs:
        endpoint: "http://{{ .Values.loki.name }}:{{ .Values.loki.port }}/otlp"
        tls:
          insecure: true

      otlp/jaeger:
        endpoint: {{ .Values.jaeger.otlpEndpoint | quote }}
        tls:
          insecure: true

      otlphttp/metrics:
        endpoint: "http://{{ .Values.victoriaMetrics.name }}:{{ .Values.victoriaMetrics.port }}/api/v1/write"
        tls:
          insecure: true

    service:
      telemetry:
        logs:
          level: debug
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp/jaeger]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlphttp/metrics]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug, otlphttp/logs]
{{- end }}
