apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.redis.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.serviceName }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          imagePullPolicy: {{ .Values.redis.pullPolicy }}
          ports:
            - containerPort: {{ .Values.redis.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.serviceName }}
spec:
  selector:
    app: {{ .Values.redis.serviceName }}
  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
  type: ClusterIP